### ISSUE TITLE
decode_integer func returns invalid vale

### ISSUE THREAD

**Issue by tjwogh0** [jnferguson/hpack-rfc7541#2]
1. In decode_integer func,

if(dst == two_N) is true, (i.e all the bits of prefix are set to 1) must increase the 'current' value before execute the loop.

I think, "for (; current < end; current++ )" -> "for (current++; current < end; current++)"

2. In get_header func,
predefined_headers.size() is 62. I think indexed header(not predefined)'s index is started at 62, it is less than predefined_headers.size() + m_queue.size(). But it is equal to predefined_headers.size(), than this function throw error.

In my opnion, 

} else if ( index > predefined_headers.size() && index < predefined_headers.size() + m_queue.size() )

to 

} else if ( index >= predefined_headers.size() && index < predefined_headers.size() + m_queue.size() )

**Comment by jnferguson** [comment]
I'm sure your point is entirely valid, it was code hashed out very quickly and interdicted upon by a somewhat autocratic employer that I never got back to. I'd have to re-read a bunch of stuff that I'm probably not going to do anytime soon.

So while you're likely entirely correct, EWONTFIXBECOZLAZY_ALSO_DEADCODE
